### ISSUE TITLE
Engine tries to lookup libs in "random" folders

### ISSUE THREAD

**Issue by 7h0m4s2** [Args-Engine/Args-Engine#364]
**Describe the bug**
When building the engine from fresh download (main) the solution tries to lookup a lib in a random folder that has no association with the project.

**Include a MRE**
 Not applicable / Issue with tooling

**Expected behavior**
The engine builds

**Screenshots**
![image](https://user-images.githubusercontent.com/48121524/132391119-23b60b16-4d6d-44fd-8547-4e168dc70544.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 - Version: 10.0.19043 Build 19043

**Additional context**
![image](https://user-images.githubusercontent.com/48121524/132391223-3df7d13f-c68a-4a18-9bbd-1ac6ffda015a.png)

**Comment by Algo-ryth-mix** [comment]
It looks like you have an installation of vcpkg with integration into Visual Studio. This modifies where the standard path for libraries is, because the Engine ships its own libraries this can lead to problems. Please remove the vcpkg installation and try again. Note that this has most likely nothing to do with your environment variables.

**Comment by Algo-ryth-mix** [comment]
Since no more information has been provided, I will close this issue. Please comment if you still experience issues
